import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { PrimaryButton, SecondaryButton, colors } from "@/components/passsafe-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useEntitlement } from "@/hooks/use-entitlement";

export default function ProScreen() {
  const router = useRouter();
  const entitlement = useEntitlement();

  const purchase = async (identifier: string) => {
    const activated = await entitlement.purchase(identifier);
    if (activated) router.back();
  };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.top}><Pressable accessibilityRole="button" accessibilityLabel="Close Pro options" onPress={() => router.back()} style={({ pressed }) => [styles.close, pressed && styles.pressed]}><MaterialIcons name="close" size={21} color={colors.text} /></Pressable></View>
    <View style={styles.hero}><View style={styles.crown}><Text style={styles.crownText}>♛</Text></View><Text style={styles.title}>Study without limits</Text><Text style={styles.subtitle}>PassSafe Pro gives you unlimited practice and a focused, ad-free study experience.</Text></View>
    <View style={styles.benefits}>{[["all-inclusive", "Unlimited practice questions"], ["visibility-off", "No banner or interstitial ads"], ["assignment", "Full mock exams and Night Before review"]].map(([icon, label]) => <View style={styles.benefit} key={label}><View style={styles.benefitIcon}><MaterialIcons name={icon as keyof typeof MaterialIcons.glyphMap} size={19} color={colors.primary} /></View><Text style={styles.benefitText}>{label}</Text></View>)}</View>
    {entitlement.isLoading ? <View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>Loading subscription options…</Text></View> : entitlement.isPro ? <View style={styles.active}><MaterialIcons name="verified" size={23} color="#FFFFFF" /><Text style={styles.activeText}>PassSafe Pro is active</Text></View> : <View style={styles.plans}>{entitlement.packages.map((item) => <Pressable key={item.identifier} disabled={entitlement.isWorking} onPress={() => purchase(item.identifier)} style={({ pressed }) => [styles.plan, pressed && styles.pressed, entitlement.isWorking && styles.dimmed]}><View style={styles.planCopy}><Text style={styles.planTitle}>{item.title || "PassSafe Pro"}</Text><Text style={styles.planDescription}>{item.description || "Unlimited food-safety practice"}</Text></View><Text style={styles.price}>{item.price}</Text><MaterialIcons name="chevron-right" size={22} color={colors.primary} /></Pressable>)}</View>}
    {entitlement.error ? <View style={styles.notice}><MaterialIcons name="info-outline" size={18} color="#92400E" /><Text style={styles.noticeText}>{entitlement.error}</Text></View> : null}
    {!entitlement.isPro && entitlement.packages.length > 0 ? <View style={styles.purchaseHint}><Text style={styles.purchaseHintText}>Your selected plan is billed through your App Store or Google Play account.</Text></View> : null}
    <View style={styles.actions}>{!entitlement.isPro && entitlement.packages.length === 1 ? <PrimaryButton label={entitlement.isWorking ? "Opening store…" : `Continue for ${entitlement.packages[0].price}`} disabled={entitlement.isWorking} onPress={() => purchase(entitlement.packages[0].identifier)} /> : null}<SecondaryButton label={entitlement.isWorking ? "Checking purchases…" : "Restore purchases"} onPress={entitlement.restore} /><SecondaryButton label="Not now" onPress={() => router.back()} /></View>
    <Text style={styles.legal}>Payment is charged to your store account after confirmation. Subscriptions renew automatically unless cancelled in your store account settings.</Text>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 30 }, top: { alignItems: "flex-end" }, close: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, hero: { alignItems: "center", marginTop: 8 }, crown: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, crownText: { color: "#FFFFFF", fontSize: 33 }, title: { color: colors.text, fontSize: 28, fontWeight: "800", textAlign: "center", marginTop: 16 }, subtitle: { color: colors.textSecondary, fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 8, maxWidth: 330 }, benefits: { marginTop: 25, gap: 12 }, benefit: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: colors.border, borderRadius: 14, minHeight: 56, paddingHorizontal: 14 }, benefitIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: "#F0FDF4", alignItems: "center", justifyContent: "center" }, benefitText: { color: colors.text, fontSize: 14, fontWeight: "700", flex: 1 }, loading: { alignItems: "center", gap: 10, paddingVertical: 28 }, loadingText: { color: colors.textSecondary, fontSize: 13 }, plans: { gap: 11, marginTop: 20 }, plan: { minHeight: 78, backgroundColor: "#FFFFFF", borderWidth: 2, borderColor: colors.primary, borderRadius: 16, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 10 }, planCopy: { flex: 1 }, planTitle: { color: colors.text, fontSize: 15, fontWeight: "800" }, planDescription: { color: colors.textSecondary, fontSize: 12, lineHeight: 16, marginTop: 3 }, price: { color: colors.primary, fontSize: 16, fontWeight: "800" }, notice: { marginTop: 18, backgroundColor: "#FFFBEB", borderWidth: 1, borderColor: "#FDE68A", borderRadius: 12, padding: 12, flexDirection: "row", gap: 9 }, noticeText: { color: "#92400E", fontSize: 12, lineHeight: 17, flex: 1 }, active: { marginTop: 24, minHeight: 64, borderRadius: 16, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 9 }, activeText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, purchaseHint: { marginTop: 16 }, purchaseHintText: { color: colors.textSecondary, fontSize: 11, lineHeight: 16, textAlign: "center" }, actions: { gap: 10, marginTop: 22 }, legal: { color: "#9CA3AF", fontSize: 10, lineHeight: 14, textAlign: "center", marginTop: 17, paddingHorizontal: 12 }, pressed: { opacity: 0.9, transform: [{ scale: 0.98 }] }, dimmed: { opacity: 0.6 },
});
