import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";

import { Card, Pill, PrimaryButton, SecondaryButton, colors } from "@/components/passsafe-ui";
import { ScreenContainer } from "@/components/screen-container";
import { usePassSafe } from "@/lib/passsafe-context";
import { languages, tracks } from "@/lib/passsafe-data";

export default function ProfileScreen() {
  const router = useRouter(); const { language, certTrack, examDate, usage, notificationsEnabled, setNotificationsEnabled, setPro, resetLearner } = usePassSafe(); const languageName = languages.find((item) => item.key === language)?.label ?? "English"; const trackName = tracks.find((item) => item.key === certTrack)?.title ?? "Manager";
  const logout = () => Alert.alert("Reset PassSafe?", "This clears local progress and returns you to onboarding.", [{ text: "Cancel", style: "cancel" }, { text: "Reset", style: "destructive", onPress: async () => { await resetLearner(); router.replace("/" as never); } }]);
  return <ScreenContainer style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.profileHead}><View style={styles.avatar}><Text style={styles.initials}>AR</Text></View><View style={styles.person}><Text style={styles.name}>Alex Rivera</Text><Text style={styles.email}>alex@passsafe.study</Text><View style={styles.streak}><Text style={styles.streakText}>🔥 12-day study streak</Text></View></View></View><Card style={styles.settings}><Text style={styles.settingsTitle}>Study settings</Text><Pressable onPress={() => router.push("/onboarding/language" as never)} style={({ pressed }) => [styles.setting, pressed && styles.pressed]}><View style={styles.settingLeft}><MaterialIcons name="language" size={21} color={colors.primary} /><View><Text style={styles.settingName}>Language</Text><Text style={styles.settingValue}>{languageName}</Text></View></View><MaterialIcons name="chevron-right" size={22} color="#9CA3AF" /></Pressable><View style={styles.divider} /><View style={styles.setting}><View style={styles.settingLeft}><MaterialIcons name="workspace-premium" size={21} color={colors.primary} /><View><Text style={styles.settingName}>Certification track</Text><Text style={styles.settingValue}>{trackName}</Text></View></View></View><View style={styles.divider} /><View style={styles.setting}><View style={styles.settingLeft}><MaterialIcons name="event" size={21} color={colors.primary} /><View><Text style={styles.settingName}>Exam date</Text><Text style={styles.settingValue}>{examDate || "Not set"}</Text></View></View></View><View style={styles.divider} /><View style={styles.setting}><View style={styles.settingLeft}><MaterialIcons name="notifications-none" size={21} color={colors.primary} /><Text style={styles.settingName}>Study reminders</Text></View><Switch value={notificationsEnabled} onValueChange={setNotificationsEnabled} trackColor={{ false: "#E5E7EB", true: "#A7F3D0" }} thumbColor="#FFFFFF" /></View></Card><Card style={styles.plan}><View><Text style={styles.settingsTitle}>{usage.isPro ? "PassSafe Pro" : "Free plan"}</Text><Text style={styles.planCopy}>{usage.isPro ? "Unlimited practice, no ads, and full mock sessions." : `${usage.answeredToday}/${50 + usage.rewardedUnlocks * 10} questions used today.`}</Text></View><Pill label={usage.isPro ? "PRO" : "FREE"} tone={usage.isPro ? "green" : "amber"} /><View style={styles.planAction}>{usage.isPro ? <SecondaryButton label="Manage Pro plan" onPress={() => setPro(false)} /> : <PrimaryButton label="Upgrade to Pro" onPress={() => setPro(true)} />}</View></Card><View style={styles.legal}><Text style={styles.legalText}>PassSafe is not affiliated with or endorsed by NRAEF. ServSafe® is a registered trademark. All questions are original practice content based on food-safety principles.</Text></View><SecondaryButton label="Log out" onPress={logout} /></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 28 }, profileHead: { flexDirection: "row", alignItems: "center", gap: 14, marginBottom: 23 }, avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, initials: { color: "#FFFFFF", fontSize: 19, fontWeight: "800" }, person: { flex: 1 }, name: { color: colors.text, fontSize: 20, fontWeight: "800" }, email: { color: colors.textSecondary, fontSize: 12, marginTop: 3 }, streak: { alignSelf: "flex-start", backgroundColor: colors.accentLight, paddingHorizontal: 9, paddingVertical: 4, borderRadius: 99, marginTop: 8 }, streakText: { color: "#B45309", fontSize: 10, fontWeight: "800" }, settings: { padding: 16 }, settingsTitle: { color: colors.text, fontSize: 15, fontWeight: "800" }, setting: { minHeight: 58, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, settingLeft: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 }, settingName: { color: colors.text, fontSize: 14, fontWeight: "700" }, settingValue: { color: colors.textSecondary, fontSize: 11, marginTop: 3 }, divider: { height: 1, backgroundColor: colors.border }, plan: { padding: 16, marginTop: 15 }, planCopy: { color: colors.textSecondary, fontSize: 12, lineHeight: 17, marginTop: 5, maxWidth: "90%" }, planAction: { marginTop: 15 }, legal: { marginVertical: 19, paddingHorizontal: 8 }, legalText: { textAlign: "center", color: colors.textSecondary, fontSize: 10, lineHeight: 15 }, pressed: { opacity: 0.88, transform: [{ scale: 0.98 }] }, });
