import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { Card, Pill, ProgressBar, ReadinessGauge, colors } from "@/components/passsafe-ui";
import { ScreenContainer } from "@/components/screen-container";
import { usePassSafe } from "@/lib/passsafe-context";
import { getQuestionTopics } from "@/lib/passsafe-data";
import { startSession } from "@/lib/session-store";

export default function ProgressScreen() {
  const router = useRouter(); const { certTrack, readiness, progress } = usePassSafe(); const topics = getQuestionTopics(certTrack);
  const drill = (topic: string) => { const session = startSession("topic", certTrack, topic); router.push({ pathname: "/session" as never, params: { id: session.id } } as never); };
  return <ScreenContainer style={styles.screen}><FlatList data={topics} keyExtractor={(item) => item.topic} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.title}>Your Readiness</Text><Text style={styles.subtitle}>{certTrack === "manager" ? "Manager" : "Food Handler"} track</Text></View><MaterialIcons name="notifications-none" size={24} color={colors.text} /></View><Card style={styles.gaugeCard}><ReadinessGauge value={readiness} size={220} /><Text style={styles.readyText}>{readiness >= 75 ? "You’re near the passing target." : "Continue practicing to reach 75%."}</Text></Card><Text style={styles.sectionTitle}>Knowledge Areas</Text></>} renderItem={({ item }) => { const data = progress[item.topic]; const value = data ? Math.round((data.correct / data.total) * 100) : 0; const barColor = value >= 80 ? colors.success : value >= 65 ? colors.accent : colors.danger; return <Card style={styles.topic}><View style={styles.topicHeading}><Text style={styles.topicName}>{item.topic}</Text><Text style={[styles.topicPercent, { color: barColor }]}>{value}%</Text></View><ProgressBar value={value} color={barColor} /><View style={styles.topicFooter}><Text style={styles.topicMeta}>{data ? `${data.correct}/${data.total} correct` : `${item.count} questions available`}</Text>{value < 50 ? <Pressable onPress={() => drill(item.topic)} style={({ pressed }) => [styles.drill, pressed && styles.pressed]}><Text style={styles.drillText}>Drill now</Text></Pressable> : <Pill label={value >= 80 ? "STRONG" : "IN PROGRESS"} tone={value >= 80 ? "green" : "amber"} />}</View></Card>; }} /></ScreenContainer>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 26, gap: 12 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }, title: { color: colors.text, fontSize: 25, fontWeight: "800" }, subtitle: { color: colors.textSecondary, fontSize: 13, marginTop: 4 }, gaugeCard: { backgroundColor: colors.background, paddingVertical: 17, alignItems: "center" }, readyText: { color: colors.textSecondary, fontSize: 12, marginTop: 7 }, sectionTitle: { color: colors.text, fontSize: 16, fontWeight: "800", marginTop: 7, marginBottom: 1 }, topic: { padding: 15 }, topicHeading: { flexDirection: "row", justifyContent: "space-between", gap: 12, marginBottom: 10 }, topicName: { color: colors.text, fontSize: 14, fontWeight: "800", flex: 1 }, topicPercent: { fontSize: 13, fontWeight: "800" }, topicFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 11 }, topicMeta: { color: colors.textSecondary, fontSize: 11 }, drill: { borderRadius: 99, backgroundColor: colors.accentLight, paddingHorizontal: 10, paddingVertical: 6 }, drillText: { color: "#B45309", fontSize: 10, fontWeight: "800" }, pressed: { opacity: 0.88, transform: [{ scale: 0.98 }] }, });
